"""Test name column addition in response Table

Revision ID: 6e2bb0bfabd4
Revises: 95e6735cb161
Create Date: 2025-12-24 11:30:48.212992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2bb0bfabd4'
down_revision: Union[str, Sequence[str], None] = '95e6735cb161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('test_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'test_name')
    # ### end Alembic commands ###
