"""remove_question_count

Revision ID: 808a9e2cb715
Revises: 96f3a24d16bb
Create Date: 2025-12-19 17:26:23.793603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808a9e2cb715'
down_revision: Union[str, Sequence[str], None] = '96f3a24d16bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'question_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
