"""Test name column addition in Test Table

Revision ID: 95e6735cb161
Revises: 808a9e2cb715
Create Date: 2025-12-23 16:01:15.436151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e6735cb161'
down_revision: Union[str, Sequence[str], None] = '808a9e2cb715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'test_name')
    # ### end Alembic commands ###
